"""
Requirements Architect — Streamlit UI (v3 — Wealthsimple Brand)

Brand palette: Wealthsimple's signature Dune (#32302F) + White (#FFFFFF).
Color psychology: Warm neutrals = trust, stability, professionalism.
Accent: Gold (#D4A843) for CTAs = confidence, premium value.
Green (#2D8C5A) for success states = growth, financial health.

Run: cd ~/career-os && source .venv/bin/activate && streamlit run execution/requirements_architect_ui.py
"""

import sys
import io
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import streamlit as st
from requirements_architect import (
    get_available_providers,
    call_ai_with_fallback,
    TRANSCRIPT_DIRECTIVE,
    REGULATION_DIRECTIVE,
)
from utils.ui import inject_css, render_header

# ── Page Config ──
st.set_page_config(
    page_title="Requirements Architect · AI Builder",
    page_icon="🏗️",
    layout="wide",
    initial_sidebar_state="expanded",
)

inject_css()

# ── State ──
if "result" not in st.session_state:
    st.session_state.result = None


# ─────────────────────────────────────
# Export Helpers
# ─────────────────────────────────────

def to_plain_text(md_text):
    """Strip markdown formatting for .txt export."""
    import re
    text = re.sub(r'#{1,6}\s*', '', md_text)     # headers
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)  # bold
    text = re.sub(r'\*(.+?)\*', r'\1', text)       # italic
    text = re.sub(r'```[\s\S]*?```', '', text)     # code blocks
    text = re.sub(r'`(.+?)`', r'\1', text)         # inline code
    text = re.sub(r'- \*\*', '- ', text)
    return text.strip()


def to_pdf(md_text):
    """Generate PDF from spec content."""
    from fpdf import FPDF
    import re

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(50, 48, 47)  # Dune
    pdf.cell(0, 12, "AI-Generated Technical Spec", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, "Generated by Requirements Architect v1.0", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    lines = md_text.split("\n")
    for line in lines:
        stripped = line.strip()
        if not stripped:
            pdf.ln(3)
            continue

        if stripped.startswith("## "):
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(50, 48, 47)
            pdf.cell(0, 8, stripped.replace("## ", ""), new_x="LMARGIN", new_y="NEXT")
            pdf.set_draw_color(212, 168, 67)  # Gold accent
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)
        elif stripped.startswith("### "):
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(70, 70, 70)
            pdf.cell(0, 7, stripped.replace("### ", ""), new_x="LMARGIN", new_y="NEXT")
        elif stripped.startswith("```"):
            continue
        elif stripped.startswith("- ") or stripped.startswith("* "):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(60, 60, 60)
            clean = re.sub(r'\*\*(.+?)\*\*', r'\1', stripped)
            pdf.cell(8, 6, chr(8226))  # bullet
            pdf.multi_cell(0, 6, clean[2:])
        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(60, 60, 60)
            clean = re.sub(r'\*\*(.+?)\*\*', r'\1', stripped)
            pdf.multi_cell(0, 6, clean)

    return pdf.output()


def to_docx(md_text):
    """Generate DOCX from spec content."""
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    import re

    doc = Document()

    # Style the title
    title = doc.add_heading("AI-Generated Technical Spec", level=0)
    title.runs[0].font.color.rgb = RGBColor(50, 48, 47)
    doc.add_paragraph("Generated by Requirements Architect v1.0",
                       style="Subtitle")

    lines = md_text.split("\n")
    in_code_block = False

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("```"):
            in_code_block = not in_code_block
            continue

        if in_code_block:
            p = doc.add_paragraph(stripped)
            p.style = "No Spacing"
            for run in p.runs:
                run.font.name = "Courier New"
                run.font.size = Pt(9)
                run.font.color.rgb = RGBColor(50, 48, 47)
            continue

        if not stripped:
            continue
        elif stripped.startswith("## "):
            h = doc.add_heading(stripped.replace("## ", ""), level=2)
            h.runs[0].font.color.rgb = RGBColor(50, 48, 47)
        elif stripped.startswith("### "):
            h = doc.add_heading(stripped.replace("### ", ""), level=3)
            h.runs[0].font.color.rgb = RGBColor(80, 80, 80)
        elif stripped.startswith("- ") or stripped.startswith("* "):
            clean = re.sub(r'\*\*(.+?)\*\*', r'\1', stripped[2:])
            doc.add_paragraph(clean, style="List Bullet")
        else:
            clean = re.sub(r'\*\*(.+?)\*\*', r'\1', stripped)
            doc.add_paragraph(clean)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


# ─────────────────────────────────────
# Sidebar
# ─────────────────────────────────────

with st.sidebar:
    st.markdown("### ⚙️ Configuration")

    st.markdown("### ⚙️ Configuration")

    mode = st.radio(
        "**Input Mode**",
        ["📝 Stakeholder Transcript", "📜 Regulatory Document"],
        help="Transcripts → PRD with user stories.\nRegulations → Compliance spec with unit tests."
    )

    # Providers
    providers = get_available_providers()
    st.markdown("---")
    st.markdown("### 🤖 AI Providers")
    if providers:
        for name, _ in providers:
            st.markdown(f"✅ **{name.capitalize()}**")
        st.caption("Smart fallback on quota/error.")
    else:
        st.error("No API keys found!")

    st.markdown("---")
    st.markdown("### 🏗️ Architecture")
    st.markdown("""
    **Layer 1** · Directive  
    **Layer 2** · Orchestration  
    **Layer 3** · Execution
    """)

    st.markdown("---")
    st.caption("**Alan Tri** · Senior BA → AI Builder")


# ─────────────────────────────────────
# Header
# ─────────────────────────────────────

render_header(
    title="Requirements Architect",
    description="From stakeholder chaos to production-ready specs — in minutes, not weeks."
)


# ─────────────────────────────────────
# Main Layout
# ─────────────────────────────────────

col1, col2 = st.columns([1, 1], gap="large")

with col1:
    st.markdown("## 📥 Input")

    upload_tab, paste_tab, sample_tab = st.tabs(["Upload", "Paste", "Samples"])

    input_text = None

    with upload_tab:
        uploaded_file = st.file_uploader(
            "Drop a .txt or .md file",
            type=["txt", "md"],
        )
        if uploaded_file:
            input_text = uploaded_file.read().decode("utf-8")
            st.text_area("Preview", input_text, height=380, disabled=True)

    with paste_tab:
        pasted = st.text_area(
            "Paste meeting notes, transcripts, or regulatory text",
            height=380,
            placeholder="Paste your raw stakeholder meeting notes, Slack threads, voice memo transcripts, or regulatory document text here...\n\nThe AI will analyze the input and generate a complete structured technical specification.",
        )
        if pasted.strip():
            input_text = pasted

    with sample_tab:
        sample_dir = Path(__file__).parent.parent / ".tmp"
        st.markdown("**Pre-loaded Wealthsimple test data:**")

        col_s1, col_s2 = st.columns(2)
        with col_s1:
            if st.button("📝 TFSA Meeting", use_container_width=True, help="A realistic stakeholder meeting about TFSA contribution optimization"):
                p = sample_dir / "sample_transcript.txt"
                if p.exists():
                    st.session_state["sample_loaded"] = p.read_text()
                    st.rerun()
        with col_s2:
            if st.button("📜 CRA TFSA Rules", use_container_width=True, help="CRA regulatory text about TFSA contribution limits and penalties"):
                p = sample_dir / "sample_regulation.txt"
                if p.exists():
                    st.session_state["sample_loaded"] = p.read_text()
                    st.rerun()

        if "sample_loaded" in st.session_state:
            input_text = st.session_state["sample_loaded"]
            st.text_area("Preview", input_text, height=320, disabled=True)


with col2:
    st.markdown("## 📤 Generated Spec")

    can_generate = input_text is not None and len(providers) > 0

    if st.button("🚀  Generate Spec", type="primary", use_container_width=True, disabled=(not can_generate)):
        if input_text:
            is_regulation = mode == "📜 Regulatory Document"
            directive = REGULATION_DIRECTIVE if is_regulation else TRANSCRIPT_DIRECTIVE
            input_label = "regulatory document" if is_regulation else "stakeholder transcript"

            with st.spinner("🧠 Analyzing and architecting requirements..."):
                try:
                    user_prompt = f"Here is the raw {input_label}:\n\n{input_text}"
                    result = call_ai_with_fallback(providers, directive, user_prompt)
                    if result:
                        st.session_state.result = result
                except SystemExit:
                    st.error("❌ All providers failed. Check your API keys.")
                except Exception as e:
                    st.error(f"❌ {e}")

    # Display result
    if st.session_state.result:
        result = st.session_state.result
        st.success("✅ Spec generated successfully!")

        # Export buttons row
        st.markdown("**Export as:**")
        dl1, dl2, dl3, dl4 = st.columns(4)
        with dl1:
            st.download_button(
                "📝 Markdown",
                result,
                file_name="spec.md",
                mime="text/markdown",
                use_container_width=True,
            )
        with dl2:
            st.download_button(
                "📄 Text",
                to_plain_text(result),
                file_name="spec.txt",
                mime="text/plain",
                use_container_width=True,
            )
        with dl3:
            st.download_button(
                "📕 PDF",
                to_pdf(result),
                file_name="spec.pdf",
                mime="application/pdf",
                use_container_width=True,
            )
        with dl4:
            st.download_button(
                "📘 DOCX",
                to_docx(result),
                file_name="spec.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                use_container_width=True,
            )

        st.markdown("---")
        st.markdown(result)

    elif not can_generate:
        st.info("👈 Upload, paste, or load sample text to get started.")


# ── Footer ──
st.markdown("---")
st.markdown("""
<div style="text-align:center; padding:1.5rem 0;">
    <p style="color:#A1A1AA !important; font-size:0.85rem; margin:0;">
        <strong style="color:#00FFAA !important;">Requirements Architect v1.0</strong>
    </p>
    <p style="color:#A1A1AA !important; font-size:0.8rem; margin:4px 0 0 0;">
        Directive → Orchestration → Execution · Built for AI Builders
    </p>
</div>
""", unsafe_allow_html=True)
