"""
Requirements Architect — Streamlit UI (v3 — Wealthsimple Brand)

Brand palette: Wealthsimple's signature Dune (#32302F) + White (#FFFFFF).
Color psychology: Warm neutrals = trust, stability, professionalism.
Accent: Gold (#D4A843) for CTAs = confidence, premium value.
Green (#2D8C5A) for success states = growth, financial health.

Run: cd ~/career-os && source .venv/bin/activate && streamlit run execution/requirements_architect_ui.py
"""

import sys
import io
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import streamlit as st
from requirements_architect import (
    get_available_providers,
    call_ai_with_fallback,
    TRANSCRIPT_DIRECTIVE,
    REGULATION_DIRECTIVE,
)

# ── Page Config ──
st.set_page_config(
    page_title="Requirements Architect · AI Builder",
    page_icon="🏗️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Theme State ──
if "theme" not in st.session_state:
    st.session_state.theme = "dark"
if "result" not in st.session_state:
    st.session_state.result = None

is_dark = st.session_state.theme == "dark"


# ─────────────────────────────────────
# Export Helpers
# ─────────────────────────────────────

def to_plain_text(md_text):
    """Strip markdown formatting for .txt export."""
    import re
    text = re.sub(r'#{1,6}\s*', '', md_text)     # headers
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)  # bold
    text = re.sub(r'\*(.+?)\*', r'\1', text)       # italic
    text = re.sub(r'```[\s\S]*?```', '', text)     # code blocks
    text = re.sub(r'`(.+?)`', r'\1', text)         # inline code
    text = re.sub(r'- \*\*', '- ', text)
    return text.strip()


def to_pdf(md_text):
    """Generate PDF from spec content."""
    from fpdf import FPDF
    import re

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(50, 48, 47)  # Dune
    pdf.cell(0, 12, "AI-Generated Technical Spec", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, "Generated by Requirements Architect v1.0", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    lines = md_text.split("\n")
    for line in lines:
        stripped = line.strip()
        if not stripped:
            pdf.ln(3)
            continue

        if stripped.startswith("## "):
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(50, 48, 47)
            pdf.cell(0, 8, stripped.replace("## ", ""), new_x="LMARGIN", new_y="NEXT")
            pdf.set_draw_color(212, 168, 67)  # Gold accent
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)
        elif stripped.startswith("### "):
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(70, 70, 70)
            pdf.cell(0, 7, stripped.replace("### ", ""), new_x="LMARGIN", new_y="NEXT")
        elif stripped.startswith("```"):
            continue
        elif stripped.startswith("- ") or stripped.startswith("* "):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(60, 60, 60)
            clean = re.sub(r'\*\*(.+?)\*\*', r'\1', stripped)
            pdf.cell(8, 6, chr(8226))  # bullet
            pdf.multi_cell(0, 6, clean[2:])
        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(60, 60, 60)
            clean = re.sub(r'\*\*(.+?)\*\*', r'\1', stripped)
            pdf.multi_cell(0, 6, clean)

    return pdf.output()


def to_docx(md_text):
    """Generate DOCX from spec content."""
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    import re

    doc = Document()

    # Style the title
    title = doc.add_heading("AI-Generated Technical Spec", level=0)
    title.runs[0].font.color.rgb = RGBColor(50, 48, 47)
    doc.add_paragraph("Generated by Requirements Architect v1.0",
                       style="Subtitle")

    lines = md_text.split("\n")
    in_code_block = False

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("```"):
            in_code_block = not in_code_block
            continue

        if in_code_block:
            p = doc.add_paragraph(stripped)
            p.style = "No Spacing"
            for run in p.runs:
                run.font.name = "Courier New"
                run.font.size = Pt(9)
                run.font.color.rgb = RGBColor(50, 48, 47)
            continue

        if not stripped:
            continue
        elif stripped.startswith("## "):
            h = doc.add_heading(stripped.replace("## ", ""), level=2)
            h.runs[0].font.color.rgb = RGBColor(50, 48, 47)
        elif stripped.startswith("### "):
            h = doc.add_heading(stripped.replace("### ", ""), level=3)
            h.runs[0].font.color.rgb = RGBColor(80, 80, 80)
        elif stripped.startswith("- ") or stripped.startswith("* "):
            clean = re.sub(r'\*\*(.+?)\*\*', r'\1', stripped[2:])
            doc.add_paragraph(clean, style="List Bullet")
        else:
            clean = re.sub(r'\*\*(.+?)\*\*', r'\1', stripped)
            doc.add_paragraph(clean)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


# ─────────────────────────────────────
# CSS — Wealthsimple Brand
# ─────────────────────────────────────

# Color Psychology:
# Dune (#32302F): Stability, professionalism, luxury — Wealthsimple's signature
# Gold (#D4A843): Confidence, premium value, call-to-action warmth
# Green (#2D8C5A): Growth, financial health, success
# Warm Gray (#8A8886): Secondary text — approachable, not sterile
# Off-white (#FAF9F7): Wealthsimple's actual background tone

DARK_CSS = """
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');

    :root {
        --ws-dune: #32302F;
        --ws-gold: #D4A843;
        --ws-green: #2D8C5A;
        --ws-warm-gray: #8A8886;
        --ws-bg-dark: #1C1B1A;
        --ws-bg-card: #262524;
        --ws-text-primary: #F5F3F0;
        --ws-text-secondary: #B8B5B0;
        --ws-border: rgba(245, 243, 240, 0.08);
    }

    .stApp {
        background: var(--ws-bg-dark);
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
    }
    .main .block-container { max-width: 1400px; padding-top: 2rem; }

    /* Typography */
    h1 { color: var(--ws-text-primary) !important; font-weight: 700 !important; letter-spacing: -0.5px; }
    h2 { color: var(--ws-text-primary) !important; font-weight: 600 !important; font-size: 1.3rem !important; }
    h3 { color: var(--ws-text-secondary) !important; font-weight: 500 !important; }
    p, li, span, div, label { color: var(--ws-text-primary) !important; }
    .stMarkdown p { color: var(--ws-text-primary) !important; line-height: 1.75; font-size: 0.95rem; }
    .stMarkdown li { color: var(--ws-text-primary) !important; line-height: 1.7; }

    /* Sidebar */
    section[data-testid="stSidebar"] {
        background: #201F1E;
        border-right: 1px solid var(--ws-border);
    }
    section[data-testid="stSidebar"] p,
    section[data-testid="stSidebar"] li,
    section[data-testid="stSidebar"] span,
    section[data-testid="stSidebar"] label { color: var(--ws-text-secondary) !important; }
    section[data-testid="stSidebar"] strong { color: var(--ws-gold) !important; }

    /* Inputs — HIGH CONTRAST */
    textarea, input[type="text"] {
        background: var(--ws-bg-card) !important;
        color: var(--ws-text-primary) !important;
        border: 1px solid rgba(245, 243, 240, 0.12) !important;
        border-radius: 8px !important;
        font-family: 'Inter', monospace !important;
        font-size: 0.9rem !important;
        caret-color: var(--ws-gold) !important;
    }
    textarea::placeholder { color: var(--ws-warm-gray) !important; }
    textarea:focus { border-color: var(--ws-gold) !important; }

    /* Tabs */
    .stTabs [data-baseweb="tab-list"] { gap: 2px; background: transparent; border-bottom: 1px solid var(--ws-border); }
    .stTabs [data-baseweb="tab"] {
        background: transparent;
        color: var(--ws-text-secondary) !important;
        padding: 10px 20px;
        border: none;
        border-bottom: 2px solid transparent;
    }
    .stTabs [aria-selected="true"] {
        color: var(--ws-gold) !important;
        border-bottom: 2px solid var(--ws-gold) !important;
        background: transparent !important;
    }

    /* Primary Button — Gold CTA */
    .stButton > button[kind="primary"] {
        background: var(--ws-gold) !important;
        color: var(--ws-bg-dark) !important;
        font-weight: 600 !important;
        border: none !important;
        border-radius: 8px !important;
        padding: 0.7rem 1.5rem !important;
        transition: all 0.2s ease !important;
        font-size: 0.95rem !important;
    }
    .stButton > button[kind="primary"]:hover {
        transform: translateY(-1px);
        box-shadow: 0 4px 16px rgba(212, 168, 67, 0.3);
        filter: brightness(1.1);
    }

    /* Secondary Buttons */
    .stButton > button:not([kind="primary"]) {
        border-radius: 8px !important;
        border: 1px solid rgba(245, 243, 240, 0.12) !important;
        color: var(--ws-text-primary) !important;
        background: var(--ws-bg-card) !important;
        transition: all 0.15s ease !important;
    }
    .stButton > button:not([kind="primary"]):hover {
        border-color: var(--ws-gold) !important;
        color: var(--ws-gold) !important;
    }

    /* Download Buttons */
    .stDownloadButton > button {
        border-radius: 8px !important;
        border: 1px solid rgba(245, 243, 240, 0.12) !important;
        color: var(--ws-text-primary) !important;
        background: var(--ws-bg-card) !important;
    }
    .stDownloadButton > button:hover {
        border-color: var(--ws-gold) !important;
    }

    /* Code blocks */
    code { background: rgba(212, 168, 67, 0.1) !important; color: var(--ws-gold) !important; padding: 2px 6px; border-radius: 4px; }
    pre { background: #161514 !important; border: 1px solid var(--ws-border) !important; border-radius: 8px !important; }
    pre code { color: var(--ws-text-primary) !important; background: transparent !important; }

    /* File uploader */
    [data-testid="stFileUploader"] { border: 1px dashed rgba(212, 168, 67, 0.25) !important; border-radius: 8px; }

    /* Alerts */
    .stSuccess { background: rgba(45, 140, 90, 0.12) !important; border-left: 3px solid var(--ws-green) !important; }
    .stInfo { background: rgba(212, 168, 67, 0.08) !important; border-left: 3px solid var(--ws-gold) !important; }
    .stError { background: rgba(220, 60, 60, 0.1) !important; border-left: 3px solid #dc3c3c !important; }

    hr { border-color: var(--ws-border) !important; }

    /* Generated output section */
    .output-header { 
        background: linear-gradient(135deg, var(--ws-bg-card) 0%, #2a2928 100%);
        border: 1px solid var(--ws-border);
        border-radius: 12px;
        padding: 1.2rem 1.5rem;
        margin-bottom: 1rem;
    }

    /* Radio buttons */
    .stRadio [role="radiogroup"] label { color: var(--ws-text-primary) !important; }
</style>
"""

LIGHT_CSS = """
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');

    :root {
        --ws-dune: #32302F;
        --ws-gold: #B8912E;
        --ws-green: #2D8C5A;
        --ws-warm-gray: #8A8886;
        --ws-bg-light: #FAF9F7;
        --ws-bg-card: #FFFFFF;
        --ws-text-primary: #32302F;
        --ws-text-secondary: #5C5A57;
        --ws-border: rgba(50, 48, 47, 0.1);
    }

    .stApp {
        background: var(--ws-bg-light);
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
    }
    .main .block-container { max-width: 1400px; padding-top: 2rem; }

    h1 { color: var(--ws-dune) !important; font-weight: 700 !important; letter-spacing: -0.5px; }
    h2 { color: var(--ws-dune) !important; font-weight: 600 !important; font-size: 1.3rem !important; }
    h3 { color: var(--ws-text-secondary) !important; font-weight: 500 !important; }
    p, li, span, div, label { color: var(--ws-text-primary) !important; }
    .stMarkdown p { color: var(--ws-text-primary) !important; line-height: 1.75; font-size: 0.95rem; }
    .stMarkdown li { color: var(--ws-text-primary) !important; line-height: 1.7; }

    section[data-testid="stSidebar"] {
        background: #FFFFFF;
        border-right: 1px solid var(--ws-border);
    }
    section[data-testid="stSidebar"] p,
    section[data-testid="stSidebar"] li,
    section[data-testid="stSidebar"] span,
    section[data-testid="stSidebar"] label { color: var(--ws-text-secondary) !important; }
    section[data-testid="stSidebar"] strong { color: var(--ws-gold) !important; }

    textarea, input[type="text"] {
        background: #FFFFFF !important;
        color: var(--ws-text-primary) !important;
        border: 1px solid #D5D3D0 !important;
        border-radius: 8px !important;
        font-family: 'Inter', monospace !important;
        font-size: 0.9rem !important;
    }
    textarea:focus { border-color: var(--ws-gold) !important; }

    .stTabs [data-baseweb="tab-list"] { gap: 2px; background: transparent; border-bottom: 1px solid var(--ws-border); }
    .stTabs [data-baseweb="tab"] {
        background: transparent;
        color: var(--ws-text-secondary) !important;
        padding: 10px 20px;
        border: none;
        border-bottom: 2px solid transparent;
    }
    .stTabs [aria-selected="true"] {
        color: var(--ws-gold) !important;
        border-bottom: 2px solid var(--ws-gold) !important;
        background: transparent !important;
    }

    .stButton > button[kind="primary"] {
        background: var(--ws-dune) !important;
        color: #FFFFFF !important;
        font-weight: 600 !important;
        border: none !important;
        border-radius: 8px !important;
        padding: 0.7rem 1.5rem !important;
        transition: all 0.2s ease !important;
    }
    .stButton > button[kind="primary"]:hover {
        transform: translateY(-1px);
        box-shadow: 0 4px 16px rgba(50, 48, 47, 0.2);
    }

    .stButton > button:not([kind="primary"]) {
        border-radius: 8px !important;
        border: 1px solid #D5D3D0 !important;
        color: var(--ws-text-primary) !important;
        background: #FFFFFF !important;
    }
    .stButton > button:not([kind="primary"]):hover {
        border-color: var(--ws-gold) !important;
    }

    .stDownloadButton > button {
        border-radius: 8px !important;
        border: 1px solid #D5D3D0 !important;
        color: var(--ws-text-primary) !important;
        background: #FFFFFF !important;
    }

    code { background: rgba(50, 48, 47, 0.06) !important; color: var(--ws-dune) !important; }
    pre { background: var(--ws-dune) !important; border-radius: 8px !important; }
    pre code { color: #F5F3F0 !important; background: transparent !important; }

    .stSuccess { background: rgba(45, 140, 90, 0.06) !important; border-left: 3px solid var(--ws-green) !important; }
    .stInfo { background: rgba(50, 48, 47, 0.04) !important; border-left: 3px solid var(--ws-warm-gray) !important; }

    hr { border-color: var(--ws-border) !important; }

    .stRadio [role="radiogroup"] label { color: var(--ws-text-primary) !important; }
</style>
"""

# Apply theme
st.markdown(DARK_CSS if is_dark else LIGHT_CSS, unsafe_allow_html=True)


# ─────────────────────────────────────
# Sidebar
# ─────────────────────────────────────

with st.sidebar:
    st.markdown("### ⚙️ Configuration")

    # Theme toggle
    theme_label = "☀️ Switch to Light" if is_dark else "🌙 Switch to Dark"
    if st.button(theme_label, use_container_width=True):
        st.session_state.theme = "light" if is_dark else "dark"
        st.rerun()

    st.markdown("---")

    mode = st.radio(
        "**Input Mode**",
        ["📝 Stakeholder Transcript", "📜 Regulatory Document"],
        help="Transcripts → PRD with user stories.\nRegulations → Compliance spec with unit tests."
    )

    # Providers
    providers = get_available_providers()
    st.markdown("---")
    st.markdown("### 🤖 AI Providers")
    if providers:
        for name, _ in providers:
            st.markdown(f"✅ **{name.capitalize()}**")
        st.caption("Smart fallback on quota/error.")
    else:
        st.error("No API keys found!")

    st.markdown("---")
    st.markdown("### 🏗️ Architecture")
    st.markdown("""
    **Layer 1** · Directive  
    **Layer 2** · Orchestration  
    **Layer 3** · Execution
    """)

    st.markdown("---")
    st.caption("**Alan Tri** · Senior BA → AI Builder")


# ─────────────────────────────────────
# Header
# ─────────────────────────────────────

st.markdown("# 🏗️ Requirements Architect")
st.markdown("*From stakeholder chaos to production-ready specs — in minutes, not weeks.*")
st.markdown("---")


# ─────────────────────────────────────
# Main Layout
# ─────────────────────────────────────

col1, col2 = st.columns([1, 1], gap="large")

with col1:
    st.markdown("## 📥 Input")

    upload_tab, paste_tab, sample_tab = st.tabs(["Upload", "Paste", "Samples"])

    input_text = None

    with upload_tab:
        uploaded_file = st.file_uploader(
            "Drop a .txt or .md file",
            type=["txt", "md"],
        )
        if uploaded_file:
            input_text = uploaded_file.read().decode("utf-8")
            st.text_area("Preview", input_text, height=380, disabled=True)

    with paste_tab:
        pasted = st.text_area(
            "Paste meeting notes, transcripts, or regulatory text",
            height=380,
            placeholder="Paste your raw stakeholder meeting notes, Slack threads, voice memo transcripts, or regulatory document text here...\n\nThe AI will analyze the input and generate a complete structured technical specification.",
        )
        if pasted.strip():
            input_text = pasted

    with sample_tab:
        sample_dir = Path(__file__).parent.parent / ".tmp"
        st.markdown("**Pre-loaded Wealthsimple test data:**")

        col_s1, col_s2 = st.columns(2)
        with col_s1:
            if st.button("📝 TFSA Meeting", use_container_width=True, help="A realistic stakeholder meeting about TFSA contribution optimization"):
                p = sample_dir / "sample_transcript.txt"
                if p.exists():
                    st.session_state["sample_loaded"] = p.read_text()
                    st.rerun()
        with col_s2:
            if st.button("📜 CRA TFSA Rules", use_container_width=True, help="CRA regulatory text about TFSA contribution limits and penalties"):
                p = sample_dir / "sample_regulation.txt"
                if p.exists():
                    st.session_state["sample_loaded"] = p.read_text()
                    st.rerun()

        if "sample_loaded" in st.session_state:
            input_text = st.session_state["sample_loaded"]
            st.text_area("Preview", input_text, height=320, disabled=True)


with col2:
    st.markdown("## 📤 Generated Spec")

    can_generate = input_text is not None and len(providers) > 0

    if st.button("🚀  Generate Spec", type="primary", use_container_width=True, disabled=(not can_generate)):
        if input_text:
            is_regulation = mode == "📜 Regulatory Document"
            directive = REGULATION_DIRECTIVE if is_regulation else TRANSCRIPT_DIRECTIVE
            input_label = "regulatory document" if is_regulation else "stakeholder transcript"

            with st.spinner("🧠 Analyzing and architecting requirements..."):
                try:
                    user_prompt = f"Here is the raw {input_label}:\n\n{input_text}"
                    result = call_ai_with_fallback(providers, directive, user_prompt)
                    if result:
                        st.session_state.result = result
                except SystemExit:
                    st.error("❌ All providers failed. Check your API keys.")
                except Exception as e:
                    st.error(f"❌ {e}")

    # Display result
    if st.session_state.result:
        result = st.session_state.result
        st.success("✅ Spec generated successfully!")

        # Export buttons row
        st.markdown("**Export as:**")
        dl1, dl2, dl3, dl4 = st.columns(4)
        with dl1:
            st.download_button(
                "📝 Markdown",
                result,
                file_name="spec.md",
                mime="text/markdown",
                use_container_width=True,
            )
        with dl2:
            st.download_button(
                "📄 Text",
                to_plain_text(result),
                file_name="spec.txt",
                mime="text/plain",
                use_container_width=True,
            )
        with dl3:
            st.download_button(
                "📕 PDF",
                to_pdf(result),
                file_name="spec.pdf",
                mime="application/pdf",
                use_container_width=True,
            )
        with dl4:
            st.download_button(
                "📘 DOCX",
                to_docx(result),
                file_name="spec.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                use_container_width=True,
            )

        st.markdown("---")
        st.markdown(result)

    elif not can_generate:
        st.info("👈 Upload, paste, or load sample text to get started.")


# ── Footer ──
st.markdown("---")
accent = "#D4A843" if is_dark else "#32302F"
text_col = "#8A8886" if is_dark else "#5C5A57"
st.markdown(f"""
<div style="text-align:center; padding:1.5rem 0;">
    <p style="color:{text_col} !important; font-size:0.85rem; margin:0;">
        <strong style="color:{accent} !important;">Requirements Architect v1.0</strong>
    </p>
    <p style="color:{text_col} !important; font-size:0.8rem; margin:4px 0 0 0;">
        Directive → Orchestration → Execution · Built for AI Builders
    </p>
</div>
""", unsafe_allow_html=True)
